name: hiimimi
version: 1.0.0+1
publish_to: none
description: Simple application for mimii.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.3.0
  firebase_auth: 4.1.5
  cloud_firestore: 4.1.0
  firebase_storage: 11.0.6
  image_picker: 0.8.6
  path_provider: 2.0.11
  convex_bottom_bar: 3.1.0+1
  intl: 0.17.0
  syncfusion_flutter_datepicker: 20.3.60
  google_fonts: 3.0.1
  font_awesome_flutter: 10.3.0
  flutter_launcher_icons: 0.11.0
  flutter: 
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/logo.png"
  min_sdk_android: 21

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

